[project]
name = "jpt"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.0.0",
    "tokenizers>=0.21.4",
    "torch>=2.7.1",
    "transformers>=4.54.1",
]
